version: '3'

services:
    training_management_webserver:
        # tag the built image like this:
        image: matthiasnoback/training_management_webserver

        # expose the container's port 80 as localhost port 8080
        ports:
            - "8081:80"

        # connect the webserver to the "front" network
        networks:
            - front

        deploy:
            replicas: 2
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 5
                window: 5s

#        volumes:
#            # make file changes to the project working immediate
#            - ./training_management/:/opt/training_management

    training_marketplace_webserver:
        image: matthiasnoback/training_marketplace_webserver

        ports:
            - "80:80"

        networks:
            - front

        deploy:
            replicas: 2
            update_config:
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 5
                window: 5s

#        volumes:
#            # make file changes to the project working immediate
#            - ./training_marketplace/:/opt/training_marketplace

networks:
    front:
        driver: overlay
