version: '3'

services:
    test:
        image: $DOCKER_HUB_USERNAME/test
        build:
            context: ./
            dockerfile: docker/test/Dockerfile
        volumes:
            - ./:/opt
