version: '3'

services:
    service:
        image: ${TEST_IMAGE_TAG}

    service_tests:
        image: $DOCKER_HUB_USERNAME/service_tests
        build:
            context: ./
            dockerfile: docker/service_tests/Dockerfile
        volumes:
            - ./:/opt
        depends_on:
            - service

    # add other services that are needed to run the service tests
