version: '3'

services:
    service:
        image: $DOCKER_HUB_USERNAME/service:latest

    integration:
        image: $DOCKER_HUB_USERNAME/integration
        build:
            context: ./
            dockerfile: docker/integration/Dockerfile
        volumes:
            - ./:/opt
        depends_on:
            - service

    # add other services that are needed to run the integration tests
